In [78]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor,plot_tree
from sklearn.model_selection import train_test_split

In [79]:
df = pd.read_csv('california_housing.csv')

In [80]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [83]:

df['pred0'] = df['MedHouseVal'].mean()
df['res0'] = df['MedHouseVal'].values - df['pred0']

x = df.iloc[:, :8].values

for i in range(1, 7):
    y = df.iloc[:, -1].values  # residue
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    clf = DecisionTreeRegressor()
    clf.fit(x_train, y_train)
    
    # Fix the list comprehension syntax
    df[f'pred{i}'] = clf.predict(x) * 0.01 + np.sum([0.01 * df[f'pred{j}'] for j in range(1, i)])
    
    df[f'res{i}'] = df['MedHouseVal'].values - df[f'pred{i}']

In [84]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal,pred0,...,pred2,res2,pred3,res3,pred4,res4,pred5,res5,pred6,res6
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526,2.068558,...,-1.072820e+09,1.072820e+09,-2.225030e+11,2.225030e+11,-4.614711e+13,4.614711e+13,-9.570911e+15,9.570911e+15,-1.985007e+18,1.985007e+18
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585,2.068558,...,-1.072820e+09,1.072820e+09,-2.225030e+11,2.225030e+11,-4.614711e+13,4.614711e+13,-9.570911e+15,9.570911e+15,-1.985007e+18,1.985007e+18
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521,2.068558,...,-1.072820e+09,1.072820e+09,-2.225030e+11,2.225030e+11,-4.614711e+13,4.614711e+13,-9.570911e+15,9.570911e+15,-1.985007e+18,1.985007e+18
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413,2.068558,...,-1.072820e+09,1.072820e+09,-2.225030e+11,2.225030e+11,-4.614711e+13,4.614711e+13,-9.570911e+15,9.570911e+15,-1.985007e+18,1.985007e+18
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422,2.068558,...,-1.072820e+09,1.072820e+09,-2.225030e+11,2.225030e+11,-4.614711e+13,4.614711e+13,-9.570911e+15,9.570911e+15,-1.985007e+18,1.985007e+18

In [71]:
final_pred-df['MedHouseVal']

0       -2.375020
1       -1.490870
2       -1.353260
3       -1.280900
4       -1.251859
           ...
20635    1.361540
20636    1.391900
20637    1.228930
20638    1.304300
20639    1.257300
Length: 20640, dtype: float64