<a href="https://colab.research.google.com/github/bammu27/ML/blob/main/Netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Netflix IMDB Scores**

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/Netflix TV Shows and Movies.csv')

In [6]:
df.head()

,index,id,title,type,description,release_year,age_certification,runtime,imdb_id,imdb_score,imdb_votes
0,0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,tt0075314,8.3,795222.0
1,1,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,tt0071853,8.2,530877.0
2,2,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,tt0079470,8.0,392419.0
3,3,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,tt0070047,8.1,391942.0
4,4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,tt0063929,8.8,72895.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5283 entries, 0 to 5282
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              5283 non-null   int64
 1   id                 5283 non-null   object
 2   title              5283 non-null   object
 3   type               5283 non-null   object
 4   description        5278 non-null   object
 5   release_year       5283 non-null   int64
 6   age_certification  2998 non-null   object
 7   runtime            5283 non-null   int64
 8   imdb_id            5283 non-null   object
 9   imdb_score         5283 non-null   float64
 10  imdb_votes         5267 non-null   float64
dtypes: float64(2), int64(3), object(6)
memory usage: 454.1+ KB

In [8]:
df.describe()

             index  release_year      runtime   imdb_score    imdb_votes
count  5283.000000   5283.000000  5283.000000  5283.000000  5.267000e+03
mean   2641.000000   2015.879992    79.199886     6.533447  2.340719e+04
std    1525.215067      7.346098    38.915974     1.160932  8.713432e+04
min       0.000000   1953.000000     0.000000     1.500000  5.000000e+00
25%    1320.500000   2015.000000    45.000000     5.800000  5.210000e+02
50%    2641.000000   2018.000000    87.000000     6.600000  2.279000e+03
75%    3961.500000   2020.000000   106.000000     7.400000  1.014400e+04
max    5282.000000   2022.000000   235.000000     9.600000  2.268288e+06

In [11]:
missing = df.isna().sum()

In [12]:
missing

index                   0
id                      0
title                   0
type                    0
description             5
release_year            0
age_certification    2285
runtime                 0
imdb_id                 0
imdb_score              0
imdb_votes             16
dtype: int64

In [13]:
df.columns

Index(['index', 'id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'imdb_id', 'imdb_score', 'imdb_votes'],
      dtype='object')

In [14]:
df['age_certification'].unique()

array(['R', 'PG', 'TV-14', 'G', 'PG-13', nan, 'TV-MA', 'TV-PG', 'TV-Y',
       'TV-G', 'TV-Y7', 'NC-17'], dtype=object)

In [15]:
df['age_certification'].value_counts()

TV-MA    792
R        548
TV-14    436
PG-13    424
PG       238
TV-PG    172
G        105
TV-Y7    104
TV-Y      94
TV-G      72
NC-17     13
Name: age_certification, dtype: int64

In [20]:
df[df['age_certification'].isnull()].head()

,index,id,title,type,description,release_year,age_certification,runtime,imdb_id,imdb_score,imdb_votes
10,10,tm44204,The Guns of Navarone,MOVIE,A team of allied saboteurs are assigned an imp...,1961,NaN,158,tt0054953,7.5,50150.0
14,14,tm16479,White Christmas,MOVIE,Two talented song-and-dance men team up after ...,1954,NaN,115,tt0047673,7.5,42373.0
15,15,tm135083,Cairo Station,MOVIE,"Qinawi, a physically challenged peddler who ma...",1958,NaN,77,tt0051390,7.5,4385.0
16,16,tm14491,The Queen,MOVIE,"In 1967, New York City is host to the Miss All...",1968,NaN,68,tt0183686,7.2,1117.0
19,19,tm27298,Saladin the Victorious,MOVIE,"Saladin, the first sultan of Egypt and Syria, ...",1963,NaN,186,tt0057357,7.6,2470.0

In [21]:
df = df.drop(['age_certification','index'],axis=1)

In [23]:
df.head()

,id,title,type,description,release_year,runtime,imdb_id,imdb_score,imdb_votes
0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,113,tt0075314,8.3,795222.0
1,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,91,tt0071853,8.2,530877.0
2,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,94,tt0079470,8.0,392419.0
3,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,133,tt0070047,8.1,391942.0
4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,30,tt0063929,8.8,72895.0

MOVIES WITH HIGHEST IMDB_SCORE

In [32]:
high_imdb_score= df[df['type']=='MOVIE'].loc[:,'imdb_score'].max()

In [34]:
df[(df['imdb_score']==high_imdb_score)&(df['type']=='MOVIE')]

,id,title,type,description,release_year,runtime,imdb_id,imdb_score,imdb_votes
24,tm76557,No Longer Kids,MOVIE,"By coincidence, Ahmad discovers that his fathe...",1979,235,tt8312792,9.0,943.0
822,tm166740,Chhota Bheem & Krishna in Mayanagari,MOVIE,Bheem and his Friends are having a great time ...,2011,66,tt16235600,9.0,5.0
2685,tm432327,C/o Kancharapalem,MOVIE,From a schoolboyâ€™s crush to a middle-aged ba...,2018,152,tt7391996,9.0,6562.0
3172,tm853783,David Attenborough: A Life on Our Planet,MOVIE,The story of life on our planet by the man who...,2020,83,tt11989890,9.0,31180.0

MOVIES WITH HIGHEST IMDB_VOTES

In [39]:
high_imdb_votes = df[df['type']=='MOVIE'].loc[:,'imdb_votes'].max()

In [42]:
df[(df['imdb_votes']==high_imdb_votes)&(df['type']=='MOVIE')]

,id,title,type,description,release_year,runtime,imdb_id,imdb_score,imdb_votes
246,tm92641,Inception,MOVIE,"Cobb, a skilled thief who commits corporate es...",2010,148,tt1375666,8.8,2268288.0

In [44]:
 release_data= df.groupby(by=['release_year']).mean()

<ipython-input-44-08593cc7e3cf>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  release_data= df.groupby(by=['release_year']).mean()

In [45]:
release_data

                 runtime  imdb_score    imdb_votes
release_year
1953          105.000000    6.800000    231.000000
1954          107.500000    7.450000  21796.000000
1956          120.000000    6.700000    590.000000
1958           77.000000    7.500000   4385.000000
1959          142.000000    6.700000     78.000000
...                  ...         ...           ...
2018           75.480218    6.530559   9339.311050
2019           75.951936    6.526168  11701.365952
2020           74.118721    6.344444   9950.611621
2021           74.823872    6.319068   9736.058651
2022           72.159341    6.263187   6247.638889

[66 rows x 3 columns]

WHICH IS BEST YEARs FOR MOVIE

In [49]:
release_data[(release_data['imdb_score']>release_data['imdb_score'].quantile(0.75))&(release_data['imdb_votes']>release_data['imdb_votes'].quantile(0.9))]

              runtime  imdb_score  imdb_votes
release_year
1975            100.5        7.35    265491.5

TOP MOVIES or SHOWS OF EACH YEAR

In [51]:
grouped_data = df.groupby('release_year')

In [54]:
def topmovie(x):
    y =  x.sort_values(by='imdb_score',ascending=False)
    return y[y['imdb_votes']>y['imdb_votes'].quantile(0.9)].head(1)


top_movie_byYear = grouped_data.apply(topmovie)

In [55]:
top_movie_byYear

,,id,title,type,description,release_year,runtime,imdb_id,imdb_score,imdb_votes
release_year,,,,,,,,,,
1954,14,tm16479,White Christmas,MOVIE,Two talented song-and-dance men team up after ...,1954,115,tt0047673,7.5,42373.0
1966,9,tm67378,The Professionals,MOVIE,An arrogant Texas millionaire hires four adven...,1966,117,tt0060862,7.3,16168.0
1969,4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,30,tt0063929,8.8,72895.0
1971,5,tm14873,Dirty Harry,MOVIE,When a madman dubbed 'Scorpio' terrorizes San ...,1971,102,tt0066999,7.7,153463.0
1972,28,ts45948,Monty Python's Fliegender Zirkus,SHOW,Monty Python's Fliegender Zirkus consisted of ...,1972,43,tt0202477,8.1,2144.0
1973,3,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,133,tt0070047,8.1,391942.0
1975,1,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,91,tt0071853,8.2,530877.0
1976,0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,113,tt0075314,8.3,795222.0
1979,2,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,94,tt0079470,8.0,392419.0
1980,7,tm98978,The Blue Lagoon,MOVIE,Two small children and a ship's cook survive a...,1980,104,tt0080453,5.8,69053.0
1981,59,tm130586,Endless Love,MOVIE,Two young kids fall in love with each other. B...,1981,116,tt0082329,4.9,8374.0
1982,54,tm41289,Annie,MOVIE,An orphan in a facility run by the mean Miss H...,1982,127,tt0083564,6.6,44866.0
1983,49,tm54450,Christine,MOVIE,Geeky student Arnie Cunningham falls for Chris...,1983,90,tt0085333,6.7,80945.0
1984,45,tm180542,Once Upon a Time in America,MOVIE,A former Prohibition-era Jewish gangster retur...,1984,229,tt0087843,8.3,342335.0
1986,44,tm111075,Stand by Me,MOVIE,"Gordie, Chris, Teddy and Vern are four friends...",1986,89,tt0092005,8.1,392790.0
1987,48,tm22327,Full Metal Jacket,MOVIE,A pragmatic U.S. Marine observes the dehumaniz...,1987,116,tt0093058,8.3,723306.0
1988,65,tm40103,Mobile Suit Gundam: Char's Counterattack,MOVIE,In UC 0093 the Federation has recovered from i...,1988,120,tt0095262,7.3,1649.0
1989,43,ts20681,Seinfeld,SHOW,A stand-up comedian and his three offbeat frie...,1989,24,tt0098904,8.9,302700.0
1990,52,tm145608,Awakenings,MOVIE,"Dr. Malcolm Sayer, a shy research physician, u...",1990,120,tt0099077,7.8,137549.0
1991,141,tm6859,My Girl,MOVIE,Vada Sultenfuss is obsessed with death. Her mo...,1991,103,tt0102492,6.9,79800.0
1992,123,tm121879,A River Runs Through It,MOVIE,A River Runs Through is a cinematographically ...,1992,123,tt0105265,7.2,59086.0
1993,142,tm186589,Cliffhanger,MOVIE,"A year after losing his friend in a tragic 4,0...",1993,112,tt0106582,6.5,128179.0
1994,101,tm122434,Forrest Gump,MOVIE,A man with a low IQ has accomplished great thi...,1994,142,tt0109830,8.8,1994599.0
1995,130,tm9323,Desperado,MOVIE,Mariachi plunges headfirst into the dark borde...,1995,104,tt0112851,7.1,183638.0
1996,102,tm106462,Happy Gilmore,MOVIE,Failed hockey player-turned-golf whiz Happy Gi...,1996,92,tt0116483,7.0,217534.0
1997,115,tm191989,Donnie Brasco,MOVIE,An FBI undercover agent infilitrates the mob a...,1997,127,tt0119008,7.7,300073.0
1998,104,tm57554,Saving Private Ryan,MOVIE,"As U.S. troops storm the beaches of Normandy, ...",1998,169,tt0120815,8.6,1346020.0
1999,124,tm44402,"Girl, Interrupted",MOVIE,"Set in the changing world of the late 1960s, S...",1999,127,tt0172493,7.3,180532.0
2000,132,tm19673,The Patriot,MOVIE,After proving himself on the field of battle i...,2000,165,tt0187393,7.2,270231.0
2001,368,tm55303,I Am Sam,MOVIE,"Sam, a neurodivergent man, has a daughter with...",2001,132,tt0277027,7.6,149082.0
2002,263,tm105329,Road to Perdition,MOVIE,Mike Sullivan works as a hit man for crime bos...,2002,117,tt0257044,7.7,263212.0
2003,267,tm139658,Big Fish,MOVIE,Throughout his life Edward Bloom has always be...,2003,125,tt0319061,8.0,435503.0
2004,273,tm88738,Closer,MOVIE,Two couples disintegrate when they begin destr...,2004,94,tt0376541,7.2,215678.0
2005,245,ts3371,Avatar: The Last Airbender,SHOW,"In a war-torn world of elemental magic, a youn...",2005,24,tt0417299,9.3,297336.0
2006,256,ts11313,DEATH NOTE,SHOW,Light Yagami is an ace student with great pros...,2006,24,tt0877057,9.0,302147.0
2007,281,tm76066,Into the Wild,MOVIE,After graduating from Emory University in 1992...,2007,140,tt0758758,8.1,611379.0
2008,229,ts4,Breaking Bad,SHOW,"When Walter White, a New Mexico chemistry teac...",2008,48,tt0903747,9.5,1727694.0
2009,351,tm142564,3 Idiots,MOVIE,In the tradition of â€œFerris Buellerâ€™s Day ...,2009,170,tt1187043,8.4,385782.0
2010,246,tm92641,Inception,MOVIE,"Cobb, a skilled thief who commits corporate es...",2010,148,tt1375666,8.8,2268288.0
2011,660,ts278,Black Mirror,SHOW,A contemporary British re-working of The Twili...,2011,59,tt2085059,8.8,515577.0
2012,662,tm41792,Django Unchained,MOVIE,"With the help of a German bounty hunter, a fre...",2012,165,tt1853728,8.4,1472668.0
2013,860,ts20682,Attack on Titan,SHOW,"Several hundred years ago, humans were nearly ...",2013,24,tt2560140,9.0,325381.0
2014,882,ts14583,BoJack Horseman,SHOW,Meet the most beloved sitcom horse of the 90s ...,2014,26,tt3398228,8.8,143584.0
2015,1143,ts8,Better Call Saul,SHOW,Six years before Saul Goodman meets Walter Whi...,2015,49,tt3032476,8.8,404920.0
2016,1154,ts42069,The Crown,SHOW,"The gripping, decades-spanning inside story of...",2016,56,tt4786824,8.7,190878.0
2017,1724,ts55668,Dark,SHOW,A missing child causes four families to help e...,2017,56,tt5753856,8.7,354443.0
2018,2112,ts80959,Sacred Games,SHOW,A link in their pasts leads an honest cop to a...,2018,50,tt10810630,8.6,85088.0
2019,3597,ts90621,Kota Factory,SHOW,"Dedicated to Shrimati SL Loney ji, Shri Irodov...",2019,42,tt9432978,9.3,66985.0
2020,3026,ts81120,The Last Dance,SHOW,A 10-part documentary chronicling the untold s...,2020,50,tt8420184,9.1,108321.0
2021,4429,ts222333,Arcane,SHOW,Amid the stark discord of twin cities Piltover...,2021,41,tt11126994,9.1,175412.0
2022,4415,ts217231,Heartstopper,SHOW,Teens Charlie and Nick discover their unlikely...,2022,28,tt10638036,8.9,28978.0